[package]
name = "promptectomy-fixtures"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
promptectomy-contracts = { path = "../promptectomy-contracts" }
serde_json.workspace = true

[lints]
workspace = true
